AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev

  DecisionLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: run.lambda_handler
      Runtime: python3.10
      CodeUri: .
      Timeout: 90
      Environment:
        Variables:
          VAR: ""
      Events:
        BookEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /
            Method: get
