AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev

  BooksLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: run.lambda_handler
      Runtime: python3.10
      CodeUri: .
      Timeout: 300
      Environment:
        Variables:
          VAR: ""
      Events:
        BookEvent:
          Type: Api
          Properties:
            Path: /
            Method: get
        SwaggerEvent:
          Type: Api
          Properties:
            Path: /apidocs
            Method: get
        SwaggerEventJSON:
          Type: Api
          Properties:
            Path: /apispec/apispec_1.json
            Method: get
